using DreamMachineGameStudio.DreamWorks.Developer.Console.Abstraction.Definitions;
using System;
using System.Collections.Generic;

namespace DreamMachineGameStudio.DreamWorks.Developer.Console.Abstraction
{
    /// <summary>
    /// Represents a buffer for storing and managing console command output entries.
    /// </summary>
    /// <remarks>This interface provides access to the collection of output entries and allows subscribers to
    /// be notified when a new entry is added.</remarks>
    internal interface IConsoleCommandOutputBuffer
    {
        #region Properties
        /// <summary>
        /// Gets a collection of output entries generated by the console command.
        /// </summary>
        IReadOnlyCollection<FConsoleCommandOutputEntry> OutputEntries { get; }
        #endregion

        #region Events
        /// <summary>
        /// Occurs when a new console command output entry is added.
        /// </summary>
        /// <remarks>This event is triggered whenever a new <see cref="FConsoleCommandOutputEntry"/> is
        /// added to the console.  Subscribers can use this event to handle or process the added entry, such as updating
        /// a user interface or logging.</remarks>
        event Action<FConsoleCommandOutputEntry> OnEntryAdded;
        #endregion
    }
}
