using System;
using System.Collections.Generic;
using DreamMachineGameStudio.DreamWorks.LoggProvider;
using DreamMachineGameStudio.DreamWorks.LogProvider.Abstraction;
using DreamMachineGameStudio.DreamWorks.Developer.Console.Abstraction;
using DreamMachineGameStudio.DreamWorks.Developer.Console.Abstraction.Definitions;

namespace DreamMachineGameStudio.DreamWorks.Developer.Console.Output
{
    /// <summary>
    /// Represents a buffer that stores and manages output entries generated by console commands.
    /// </summary>
    /// <remarks>This class implements <see cref="IConsoleCommandOutputBuffer"/> to provide access to the
    /// collection of output entries and <see cref="IDeveloperConsoleInitializer"/> to handle initialization and
    /// shutdown of the console command system. It listens for executed commands and logs their results, adding them to
    /// the output buffer.</remarks>
    internal sealed class FConsoleCommandOutputBuffer : IConsoleCommandOutputBuffer, IDeveloperConsoleInitializer
    {
        #region Fields
        private readonly List<FConsoleCommandOutputEntry> entries;

        private readonly IConsoleCommandActivator commandActivator;
        #endregion

        #region Constructors
        internal FConsoleCommandOutputBuffer(IConsoleCommandActivator commandActivator)
        {
            this.commandActivator = commandActivator;

            entries = new List<FConsoleCommandOutputEntry>();
        }
        #endregion

        #region IConsoleCommandOutputBuffer Implementation
        public event Action<FConsoleCommandOutputEntry> OnEntryAdded;

        IReadOnlyCollection<FConsoleCommandOutputEntry> IConsoleCommandOutputBuffer.OutputEntries => entries;
        #endregion

        #region IDeveloperConsoleInitializer Implementation
        void IDeveloperConsoleInitializer.Initialize()
        {
            commandActivator.OnCommandExecuted += OnCommandExecuted;
        }

        void IDeveloperConsoleInitializer.ShutDown()
        {
            commandActivator.OnCommandExecuted -= OnCommandExecuted;
        }
        #endregion

        #region Private Methods
        private void OnCommandExecuted(FConsoleCommandExecutionResult result)
        {
            FConsoleCommandOutputEntry entry = new FConsoleCommandOutputEntry(result.Message, result.WasSuccessful ? EConsoleCommandOutputType.Log : EConsoleCommandOutputType.Error);

            entries.Add(entry);

            OnEntryAdded?.Invoke(entry);
        }
        #endregion
    }
}