namespace DreamMachineGameStudio.DreamWorks.Developer.Console.Abstraction.Definitions
{
    /// <summary>
    /// Specifies the type of output generated by a console command.
    /// </summary>
    public enum EConsoleCommandOutputType : byte
    {
        /// <summary>
        /// Represents the absence of any specific value or option.
        /// </summary>
        None = 0,

        /// <summary>
        /// Represents the log level used for logging operations.
        /// </summary>
        Log = 1,

        /// <summary>
        /// Represents a warning log level, typically used to indicate potential issues or unexpected behavior that does
        /// not prevent the application from continuing to function.
        /// </summary>
        Warning = 2,

        /// <summary>
        /// Represents an error state or condition.
        /// </summary>
        Error = 3,

        /// <summary>
        /// Represents a command operation in the system.
        /// </summary>
        Command = 4
    }
}